### ISSUE TITLE
Unresolvable Dependencies

### ISSUE THREAD

**Issue by thomashunziker** [mpay24/mpay24-java#2]
When only the maven central repository is used not all dependencies can be resolved. To be specific all modules from the group _org.apache.cxf_ and _org.apache.cxf.services.ws-discovery_ cannot be resolved.

It seems as the SDK includes also server side stuff like the servlet API from JBoss. Further dedicated JAXB bindings seems to be added which make no sense when Java 6 is used. This is sad because those issues make the SDK useless in a production environment where you cannot include for a single SDK around 50 additional jars.

**Comment by renefeldermpay24** [comment]
Hi Thomas,
can you please be more specific which dependencies cannot be resolved. Then I can try to find out where they are located.

You will also need the JBoss Repository which is already included in the pom:
 `<repositories>
    <repository>
      <id>JBoss Repository</id>
      <url>https://repository.jboss.org/nexus/content/groups/public/</url>
    </repository>
  </repositories>` 

I can try to reduce the dependencies on our side but most of them are coming transitiv from jbossws-cxf-client. I will check if we can also get along with cxf only which should also reduce the dependency tree.

**Comment by thomashunziker** [comment]
Dear Rene,
The issues is solvable by adding this additional repository. However I see two issues:
1) You do not mention that in the `installation` instructions.
2) It makes everything more complex for an average developer. Especially when you have to comply with PCI DSS because you have to check this additional repository for hostile packages.

We will use directly the SOAP / WSDL interface and import the stubs via `wsimport`.

Anyway thank you for your help.

Regards,
Thomas

**Comment by renefeldermpay24** [comment]
Hi Thomas,
I removed the dependency to jboss at all. Only dependency to CXF is needed. New version 1.1.0.0 is out. Give it a try.
br
Rene
