### ISSUE TITLE
SubBrand in PaymentType not considered

### ISSUE THREAD

**Issue by d00ndy** [mpay24/mpay24-java#5]
The SubBrand  is not considered in the PaymentType. Please add also the SubBrand to the PaymentType.

**Comment by adhalla** [comment]
how to use SubBrand? is not possible in java sdk?

**Comment by renefeldermpay24** [comment]
Hello,
what do you mean when you say that the SubBrand is not considered? Are you talking about PaymentType or the Brand within PaymentTypeData? 

PaymentType is used to define the InclusionList. The InclusionList is used on the Payment Page that is shown to the Customer to specify which payments should be shown to the customer. So for example if a merchant has CC and Paypal you can specify that only CC should be shown. 

The PaymentType is a mixture of the general Type (e.g. CC) and the Brand (e.g. Visa) In general you can specify the PaymentType CC, which is used for all kind of Credit Cards. You can also specify the PaymentType CreditCard_Visa which includes the SubBrand Visa.

The Brand itself specifies SubBrands on the PaymentTypeData. So if you look into the Class CreditCardPaymentType you can specify if this payment is done using Brand VISA, MASTERCARD, DINERS, JCB, AMEX. 

Where do you miss the SubBrand? It should be already there.

**Comment by zirnipa** [comment]
Hi,
its possible to extend the preSelection with a SubBrand. See: https://docs.mpay24.com/docs/mdxi-xml#section-payment

e.g. If a specific EPS bank should be preselected for the customer.

```
<PaymentTypes Enable="true">
 <Payment Type="EPS" Brand="EPS" SubBrand="500"/>
</PaymentTypes>
```

regards,
Patrick
